name: Tests and release

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  workflow_dispatch:

env:
  CRATE_NAME: trash-rs-cli
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  build:
    name: ${{ matrix.platform.os-name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          # Platforms that don't work:
          #
          # - sparc64-unknown-linux-gnu - cannot compile openssl-sys
          # - x86_64-unknown-illumos - weird error compiling openssl - "bin/sh: 1: granlib: not found"

          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: trash
            name: trash-FreeBSD-x86_64.tar.gz

          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: trash
            name: trash-Linux-x86_64-musl.tar.gz
          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: trash
            name: trash-Linux-aarch64-musl.tar.gz
          - os-name: Linux-arm
            runs-on: ubuntu-20.04
            target: arm-unknown-linux-musleabi
            bin: trash
            name: trash-Linux-arm-musl.tar.gz
          - os-name: Linux-i686
            runs-on: ubuntu-20.04
            target: i686-unknown-linux-musl
            bin: trash
            name: trash-Linux-i686-musl.tar.gz

          - os-name: Linux-powerpc
            runs-on: ubuntu-20.04
            target: powerpc-unknown-linux-gnu
            bin: trash
            name: trash-Linux-powerpc-gnu.tar.gz

          - os-name: Linux-powerpc64
            runs-on: ubuntu-20.04
            target: powerpc64-unknown-linux-gnu
            bin: trash
            name: trash-Linux-powerpc64-gnu.tar.gz

          - os-name: Linux-powerpc64le
            runs-on: ubuntu-20.04
            target: powerpc64le-unknown-linux-gnu
            bin: trash
            name: trash-Linux-powerpc64le.tar.gz

          - os-name: Linux-riscv64
            runs-on: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu
            bin: trash
            name: trash-Linux-riscv64gc-gnu.tar.gz
          - os-name: Linux-s390x
            runs-on: ubuntu-20.04
            target: s390x-unknown-linux-gnu
            bin: trash
            name: trash-Linux-s390x-gnu.tar.gz

          - os-name: NetBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-netbsd
            bin: trash
            name: trash-NetBSD-x86_64.tar.gz

          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            bin: trash.exe
            name: trash-Windows-aarch64.zip

          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            bin: trash.exe
            name: trash-Windows-i686.zip

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            bin: trash.exe
            name: trash-Windows-x86_64.zip
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            bin: trash
            name: trash-Darwin-x86_64.tar.gz
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            bin: trash
            name: trash-Darwin-aarch64.tar.gz
        toolchain:
          - stable
        include:
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-20.04
              target: x86_64-unknown-linux-musl
              bin: trash
            toolchain: beta
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-20.04
              target: x86_64-unknown-linux-musl
              bin: trash
            toolchain: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: false
          use-rust-cache: false
          # This works around the issue in https://github.com/cross-rs/cross/issues/1450. The `main`
          # branch updated its images long ago, but the last cross release, 0.2.5, is still using
          # Ubuntu 16.04 as the base for some images.
          cross-version: 4090beca3cfffa44371a5bba524de3a578aa46c3
        if: ${{ !matrix.platform.skip-tests }}

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: trash
          target: ${{ matrix.platform.target }}
          release-tag-prefix: "not-set-release-is-created-below"
        if: matrix.toolchain == 'stable'

  create_release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    needs:
      - build
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Check artifacts
        run: ls -la .
      - name: Generate artifact attestation
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: '*'
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}